import type { ActivityCategory } from "./types";

export const CATEGORIES: ActivityCategory[] = [
  "Study",
  "Code",
  "Exercise",
  "Read",
  "Meeting",
  "Entertainment",
  "Travel",
  "Food",
  "Sleep",
  "Health",
  "Social",
  "Finance",
  "Creative",
  "Chores",
  "Custom",
];

export const CATEGORY_COLORS: Record<ActivityCategory, string> = {
  Study: "#4A90D9",
  Code: "#7C4DFF",
  Exercise: "#43A047",
  Read: "#FB8C00",
  Meeting: "#00ACC1",
  Entertainment: "#E91E63",
  Travel: "#009688",
  Food: "#8D6E63",
  Sleep: "#5C6BC0",
  Health: "#26A69A",
  Social: "#AB47BC",
  Finance: "#FFA726",
  Creative: "#EC407A",
  Chores: "#8D8D8D",
  Custom: "#78909C",
};

export const MOODS = ["😊", "🙂", "🎯", "📖", "💻", "😴", "😢", "😭", "😡"];
export const MOOD_SCORE: Record<string, number> = {
  "😡": 1,
  "😭": 1,
  "😢": 2,
  "😴": 2,
  "📖": 3,
  "💻": 3,
  "🎯": 4,
  "🙂": 4,
  "😊": 5,
};

const CATEGORY_KEYWORDS: Record<ActivityCategory, string[]> = {
  Study: [
    "study",
    "lecture",
    "class",
    "homework",
    "assignment",
    "exam",
    "quiz",
    "course",
    "lesson",
    "tutor",
    "revision",
    "notes",
    "chapter",
    "textbook",
    "tutorial",
    "seminar",
    "workshop",
  ],
  Code: [
    "code",
    "coding",
    "programming",
    "debug",
    "deploy",
    "build",
    "commit",
    "pr",
    "pull request",
    "refactor",
    "dev",
    "develop",
    "api",
    "bug",
    "fix",
    "feature",
    "script",
    "terminal",
    "git",
    "github",
    "merge",
    "hackathon",
    "algorithm",
  ],
  Exercise: [
    "gym",
    "workout",
    "run",
    "running",
    "walk",
    "walking",
    "yoga",
    "swim",
    "swimming",
    "cycle",
    "cycling",
    "sport",
    "exercise",
    "jog",
    "jogging",
    "lift",
    "stretch",
    "cardio",
    "hiit",
    "football",
    "cricket",
    "badminton",
    "tennis",
    "push",
    "pull",
  ],
  Read: [
    "read",
    "reading",
    "book",
    "article",
    "blog",
    "newsletter",
    "manga",
    "novel",
    "paper",
    "journal",
    "ebook",
    "magazine",
    "comic",
    "fiction",
    "documentation",
  ],
  Meeting: [
    "meeting",
    "standup",
    "call",
    "sync",
    "interview",
    "catch up",
    "discussion",
    "conference",
    "zoom",
    "meet",
    "1:1",
    "one-on-one",
  ],
  Entertainment: [
    "watch",
    "movie",
    "film",
    "series",
    "show",
    "netflix",
    "youtube",
    "gaming",
    "game",
    "play",
    "music",
    "concert",
    "browse",
    "scroll",
    "instagram",
    "twitter",
    "tiktok",
    "reel",
    "podcast",
    "anime",
    "stream",
    "audiobook",
    "puzzle",
  ],
  Travel: [
    "travel",
    "commute",
    "drive",
    "driving",
    "bus",
    "train",
    "flight",
    "trip",
    "journey",
    "uber",
    "auto",
    "metro",
  ],
  Food: [
    "eat",
    "eating",
    "lunch",
    "dinner",
    "breakfast",
    "snack",
    "cook",
    "cooking",
    "meal",
    "food",
    "cafe",
    "coffee",
    "restaurant",
    "bake",
    "baking",
    "tea",
    "beer",
    "wine",
    "brunch",
    "takeout",
    "delivery",
  ],
  Sleep: ["sleep", "nap", "rest", "bed", "wake", "morning routine"],
  Health: [
    "doctor",
    "hospital",
    "clinic",
    "medicine",
    "therapy",
    "physio",
    "dentist",
    "checkup",
    "prescription",
    "mental health",
    "massage",
    "sauna",
    "optician",
    "blood",
    "vaccine",
  ],
  Social: [
    "friend",
    "friends",
    "family",
    "party",
    "hangout",
    "outing",
    "dinner with",
    "lunch with",
    "coffee with",
    "date",
    "wedding",
    "event",
    "bbq",
    "reunion",
    "potluck",
  ],
  Finance: [
    "budget",
    "expense",
    "invoice",
    "pay",
    "payment",
    "bank",
    "tax",
    "investment",
    "stock",
    "crypto",
    "money",
    "salary",
    "bills",
    "insurance",
    "subscription",
    "portfolio",
  ],
  Creative: [
    "draw",
    "drawing",
    "sketch",
    "paint",
    "painting",
    "design",
    "write",
    "writing",
    "poem",
    "journal",
    "craft",
    "photo",
    "photography",
    "edit",
    "video",
    "music",
    "animation",
    "diy",
    "sew",
    "knit",
    "garden",
    "pottery",
  ],
  Chores: [
    "clean",
    "cleaning",
    "laundry",
    "wash",
    "dishes",
    "grocery",
    "groceries",
    "shop",
    "shopping",
    "vacuum",
    "organise",
    "organize",
    "tidy",
    "repair",
    "maintenance",
    "declutter",
    "recycling",
    "meal prep",
  ],
  Custom: [],
};

const EMOJI_MAP: [string[], string][] = [
  [["gym", "workout", "lift", "weights"], "🏋️"],
  [["run", "running", "jog", "jogging"], "🏃"],
  [["walk", "walking"], "🚶"],
  [["yoga", "stretch", "meditat"], "🧘"],
  [["swim", "swimming", "pool"], "🏊"],
  [["cycle", "cycling", "bike", "bicycle"], "🚴"],
  [["football", "soccer"], "⚽"],
  [["cricket"], "🏏"],
  [["badminton"], "🏸"],
  [["tennis"], "🎾"],
  [["basketball"], "🏀"],
  [
    [
      "code",
      "coding",
      "programming",
      "debug",
      "dev",
      "develop",
      "script",
      "git",
      "commit",
      "deploy",
      "build",
    ],
    "💻",
  ],
  [["bug", "fix", "refactor"], "🐛"],
  [["api", "backend", "server"], "⚙️"],
  [["study", "revision", "notes", "chapter"], "📚"],
  [["lecture", "class", "lesson"], "🎓"],
  [["homework", "assignment"], "📝"],
  [["exam", "quiz", "test"], "📋"],
  [["read", "reading", "book", "novel", "ebook"], "📖"],
  [["article", "blog", "newsletter"], "📰"],
  [["manga"], "🗒️"],
  [["meeting", "standup", "sync", "1:1"], "🤝"],
  [["call", "zoom", "meet"], "📞"],
  [["interview"], "💼"],
  [["movie", "film"], "🎬"],
  [["series", "show", "netflix"], "📺"],
  [["youtube"], "▶️"],
  [["gaming", "game", "play"], "🎮"],
  [["music", "concert", "listen"], "🎵"],
  [["instagram", "tiktok", "scroll", "browse"], "📱"],
  [["travel", "trip", "journey"], "✈️"],
  [["commute", "drive", "driving"], "🚗"],
  [["bus"], "🚌"],
  [["train", "metro"], "🚇"],
  [["uber", "auto"], "🛺"],
  [["lunch"], "🍱"],
  [["dinner"], "🍽️"],
  [["breakfast"], "🥐"],
  [["coffee", "cafe"], "☕"],
  [["snack"], "🍎"],
  [["cook", "cooking", "bake", "baking"], "👨‍🍳"],
  [["restaurant"], "🍴"],
  [["sleep", "nap"], "😴"],
  [["rest", "relax"], "🛋️"],
  [["morning routine", "wake"], "🌅"],
  [["doctor", "hospital", "clinic", "checkup"], "🏥"],
  [["medicine", "prescription"], "💊"],
  [["therapy", "mental health"], "🧠"],
  [["dentist"], "🦷"],
  [["friend", "hangout", "outing", "party"], "🎉"],
  [["family"], "👨‍👩‍👧"],
  [["date"], "❤️"],
  [["wedding"], "💒"],
  [["budget", "expense", "finance", "money"], "💰"],
  [["invoice", "tax"], "🧾"],
  [["investment", "stock", "crypto"], "📈"],
  [["draw", "drawing", "sketch"], "✏️"],
  [["paint", "painting"], "🎨"],
  [["design"], "🖼️"],
  [["write", "writing", "journal", "poem"], "🖊️"],
  [["photo", "photography"], "📷"],
  [["clean", "cleaning", "vacuum", "tidy"], "🧹"],
  [["laundry", "wash"], "🧺"],
  [["dishes"], "🍽️"],
  [["grocery", "groceries", "shopping", "shop"], "🛒"],
];

const MOOD_EMOJI_MAP: [string[], string][] = [
  [["happy", "joy", "joyful", "delight", "wonderful", "great", "amazing"], "😊"],
  [["smile", "good", "nice", "pleasant", "alright", "fine", "okay"], "🙂"],
  [["sad", "sadness", "unhappy", "down", "blue", "melancholy", "gloomy"], "😢"],
  [["cry", "crying", "terrible", "awful", "horrible", "devastat", "heartbreaking"], "😭"],
  [["angry", "mad", "frustrat", "annoyed", "irritat", "furious", "rage"], "😡"],
  [["focus", "focused", "deep work", "concentrat", "productive", "flow"], "🎯"],
  [["tired", "exhausted", "fatigue", "drained", "sleepy", "nap"], "😴"],
  [["learn", "learning", "study", "reading", "research"], "📖"],
  [["work", "office", "job", "working", "meeting", "busy"], "💻"],
];

function kwMatch(text: string, kw: string): boolean {
  if (kw.length <= 4) {
    return new RegExp(`(?:^|\\s|[^a-z])${kw}(?:$|\\s|[^a-z])`, "i").test(text);
  }
  return text.includes(kw);
}

const DURATION_REGEX = /(\d+(?:\.\d+)?)\s*(hours?|hrs?|h|minutes?|mins?|m)\b/i;

export function detectDuration(name: string): number | null {
  const match = name.match(DURATION_REGEX);
  if (!match) return null;
  const val = parseFloat(match[1]);
  if (Number.isNaN(val) || val <= 0) return null;
  const unit = match[2].toLowerCase();
  if (unit.startsWith("h")) return Math.round(val * 60);
  return Math.round(val);
}

export function detectCategory(name: string): ActivityCategory | null {
  const lower = name.toLowerCase();
  for (const [cat, keywords] of Object.entries(CATEGORY_KEYWORDS) as [
    ActivityCategory,
    string[],
  ][]) {
    if (cat === "Custom") continue;
    if (keywords.some((kw) => kwMatch(lower, kw))) return cat;
  }
  return null;
}

export function detectMood(name: string): string | null {
  const lower = name.toLowerCase();
  for (const [keywords, emoji] of MOOD_EMOJI_MAP) {
    if (keywords.some((kw) => kwMatch(lower, kw))) return emoji;
  }
  return null;
}

export const CATEGORY_HEALTH: Record<ActivityCategory, { ideal: number; max: number }> = {
  Sleep: { ideal: 480, max: 600 },
  Exercise: { ideal: 60, max: 120 },
  Study: { ideal: 120, max: 300 },
  Code: { ideal: 180, max: 480 },
  Read: { ideal: 60, max: 180 },
  Meeting: { ideal: 60, max: 120 },
  Entertainment: { ideal: 60, max: 120 },
  Travel: { ideal: 30, max: 180 },
  Food: { ideal: 60, max: 120 },
  Health: { ideal: 60, max: 180 },
  Social: { ideal: 120, max: 300 },
  Finance: { ideal: 30, max: 120 },
  Creative: { ideal: 90, max: 240 },
  Chores: { ideal: 60, max: 120 },
  Custom: { ideal: 60, max: 240 },
};
